### ISSUE TITLE
Can I NOT await for onesignal result?

### ISSUE THREAD

**Issue by pierroo** [OneSignal/onesignal-node-api#28]
### How can we help?

I am using the "client.createNotification(notification)" function in my node JS API.

Since I actually don't care about the returned info from this promise, can I just call it without await and keep doing my API stuff and return the rest that doesn't rely at all on the result of this onesignal resolution?

Basically I only want to trigger the notification sending from onesignal and ignore the rest.

WHY? Because sometimes Onesignal has response time issue for whatever reason (crash / maintenance / whatever), or even throws unknown error etc; all the above crashing my heroku dynos / job, or making my API super slow since all my dynos may be either crashed by onesignal issue or pending for their response time.

Thank you for your help!

Extra information if that helps:

Here are some of the errors that constantly crash the associated heroku dynos and seems to happen randomly:

```
/app/node_modules/@onesignal/node-onesignal/dist/apis/exception.js:20
Oct 25 19:16:16Z myapp-name app/web.8         var _this = _super.call(this, "HTTP-Code: " + code + "\nMessage: " + JSON.stringify(body)) || this;
Oct 25 19:16:16Z myapp-name app/web.8                            ^
Oct 25 19:16:16Z myapp-name app/web.8 Error: HTTP-Code: 500
Oct 25 19:16:16Z myapp-name app/web.8 Message: "Unknown API Status Code!\nBody: \"[object Object]\""
Oct 25 19:16:16Z myapp-name app/web.8     at new ApiException (/app/node_modules/@onesignal/node-onesignal/dist/apis/exception.js:20:28)
Oct 25 19:16:16Z myapp-name app/web.8     at DefaultApiResponseProcessor.<anonymous> (/app/node_modules/@onesignal/node-onesignal/dist/apis/DefaultApi.js:781:31)
Oct 25 19:16:16Z myapp-name app/web.8     at step (/app/node_modules/@onesignal/node-onesignal/dist/apis/DefaultApi.js:46:23)
Oct 25 19:16:16Z myapp-name app/web.8     at Object.next (/app/node_modules/@onesignal/node-onesignal/dist/apis/DefaultApi.js:27:53)
```

OR

```
Oct 22 18:35:00Z myapp-name app/web.8 			reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
Oct 22 18:35:00Z myapp-name app/web.8 			       ^
Oct 22 18:35:00Z myapp-name app/web.8 FetchError: request to https://onesignal.com/api/v1/notifications failed, reason: connect ETIMEDOUT 104.18.225.52:443
Oct 22 18:35:00Z myapp-name app/web.8     at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1483:11)
Oct 22 18:35:00Z myapp-name app/web.8     at ClientRequest.emit (node:events:513:28)
Oct 22 18:35:00Z myapp-name app/web.8     at TLSSocket.socketErrorListener (node:_http_client:494:9)
Oct 22 18:35:00Z myapp-name app/web.8     at TLSSocket.emit (node:events:513:28)
Oct 22 18:35:00Z myapp-name app/web.8     at emitErrorNT (node:internal/streams/destroy:157:8)
Oct 22 18:35:00Z myapp-name app/web.8     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
Oct 22 18:35:00Z myapp-name app/web.8     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
Oct 22 18:35:00Z myapp-name app/web.8   type: 'system',
Oct 22 18:35:00Z myapp-name app/web.8   errno: 'ETIMEDOUT',
Oct 22 18:35:00Z myapp-name app/web.8   code: 'ETIMEDOUT'
```

with the awaited function being:
```
const sendNotif = async (content, listUids, notification) => {
  if (!content || !listUids || listUids.length === 0) return
  return new Promise(async (resolve) => {
    const app_key_provider = {
        getToken() {
            return process.env.ONESIGNAL_REST_API_KEY
        }
    };
    const configuration = OneSignal.createConfiguration({
      authMethods: {
          app_key: {
            tokenProvider: app_key_provider
          }
      }
    });
    const client = new OneSignal.DefaultApi(configuration);
    let notification = new OneSignal.Notification();
    notification.app_id = process.env.ONESIGNAL_APP_ID;
    notification.include_player_ids = listUids
    notification.contents = {
      en: content
    };
    const { id } = await client.createNotification(notification);
    resolve(id)
  })
}
```
### Code of Conduct
- [X] I agree to follow this project's Code of Conduct

**Comment by kesheshyan** [comment]
Hey @pierroo ! Thanks for you question. Yes, you may not await for the result if you don't need the result. Since await/async in JS/TS still uses promises under the hood you can simply use standard promise workflow for all the async operations:
```ts
client.createNotification(notification).then();
```

or if you need result:

```ts
client.createNotification(notification).then(({id}) => {
  resolve(id);
});
```
