### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tony-schumacher** [OneSignal/onesignal-node-api#32]
### What happened?

If I use the `getPlayers()` API, it throws a none readable exception. All other APIs work.

### Steps to reproduce?

```Markdown
1. Install @onesignal/node-onesignal
2. call `client.getPlayers(appid, '300', 0);`
```

### What did you expect to happen?

Retrieve a list of players.

### Relevant log output

```Shell
Message: "Unknown API Status Code!\nBody: \"[object Object]\""
    at new ApiException (/Users/tonyschumacher/git/terra-backend/node_modules/@onesignal/node-onesignal/apis/exception.ts:12:9)
    at DefaultApiResponseProcessor.<anonymous> (/Users/tonyschumacher/git/terra-backend/node_modules/@onesignal/node-onesignal/apis/DefaultApi.ts:1577:15)
    at step (/Users/tonyschumacher/git/terra-backend/node_modules/@onesignal/node-onesignal/dist/apis/DefaultApi.js:46:23)
    at Object.next (/Users/tonyschumacher/git/terra-backend/node_modules/@onesignal/node-onesignal/dist/apis/DefaultApi.js:27:53)
    at /Users/tonyschumacher/git/terra-backend/node_modules/@onesignal/node-onesignal/dist/apis/DefaultApi.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/tonyschumacher/git/terra-backend/node_modules/@onesignal/node-onesignal/dist/apis/DefaultApi.js:17:12)
    at DefaultApiResponseProcessor.getPlayers (/Users/tonyschumacher/git/terra-backend/node_modules/@onesignal/node-onesignal/dist/apis/DefaultApi.js:1199:16)
    at /Users/tonyschumacher/git/terra-backend/node_modules/@onesignal/node-onesignal/types/ObservableAPI.ts:456:107
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 400,
  body: 'Unknown API Status Code!\nBody: "[object Object]"'
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emdrayallday** [comment]
Seeing a similar result calling `client.getPlayers(appId)`

**Comment by nan-li** [comment]
Closing due to oudated, looks like same issue as https://github.com/OneSignal/onesignal-node-api/issues/19
