### ISSUE TITLE
[Bug]: 1.0.0-beta5 package broken

### ISSUE THREAD

**Issue by bishsbytes** [OneSignal/onesignal-node-api#38]
### What happened?

The latest NPM package doesn't contain the 'dist' folder, so the module can't be included.

### Steps to reproduce?

```Markdown
Install 1.0.0-beta5 into project and try to run.
```

### What did you expect to happen?

To work.

Have had to fix my dependency to 1.0.0-beta4 for my project to build and run.

### Relevant log output

```Shell
Nov 15 16:45:51 ip-xxx-xxx-xxx web: Error: Cannot find module '/var/app/current/dist/apps/api-team/node_modules/@onesignal/node-onesignal/dist/index.js'
Nov 15 16:45:51 ip-xxx-xxx-xxx web: at createEsmNotFoundErr (node:internal/modules/cjs/loader:1012:15)
Nov 15 16:45:51 ip-xxx-xxx-xxx web: at finalizeEsmResolution (node:internal/modules/cjs/loader:1005:15)
Nov 15 16:45:51 ip-xxx-xxx-xxx web: at resolveExports (node:internal/modules/cjs/loader:522:14)
Nov 15 16:45:51 ip-xxx-xxx-xxx web: at Function.Module._findPath (node:internal/modules/cjs/loader:562:31)
Nov 15 16:45:51 ip-xxx-xxx-xxx web: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27)
Nov 15 16:45:51 ip-xxx-xxx-xxx web: at Function.Module._load (node:internal/modules/cjs/loader:833:27)
Nov 15 16:45:51 ip-xxx-xxx-xxx web: at Module.require (node:internal/modules/cjs/loader:1057:19)
Nov 15 16:45:51 ip-xxx-xxx-xxx web: at require (node:internal/modules/cjs/helpers:103:18)
Nov 15 16:45:51 ip-xxx-xxx-xxx web: at Object.4124 (/var/app/current/dist/apps/api-team/main.js:57:952744)
Nov 15 16:45:51 ip-xxx-xxx-xxx web: at __webpack_require__ (/var/app/current/dist/apps/api-team/main.js:57:972415) {
Nov 15 16:45:51 ip-xxx-xxx-xxx web: code: 'MODULE_NOT_FOUND',
Nov 15 16:45:51 ip-xxx-xxx-xxx web: path: '/var/app/current/dist/apps/api-team/node_modules/@onesignal/node-onesignal/package.json'
Nov 15 16:45:51 ip-xxx-xxx-xxx web: }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by theprometeus** [comment]
Yeah, suddenly broke our applications.
Will be reverting temporarily to beta4 until it's fixed.

**Comment by brandellcassio** [comment]
Even for beta4,  I'm receiving this error.

**Comment by kesheshyan** [comment]
It seems like I was able to fix this issue. Please checkout out to the version 1.0.0-beta7

Please feel free to reopen this issue if the problem persists.
